// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
//
// Run: spacetime generate --lang go --out-dir module_bindings

package module_bindings

import (
	"github.com/clockworklabs/spacetimedb-go/bsatn"
	"github.com/clockworklabs/spacetimedb-go/client"
)

// RemoteTables provides typed access to all tables in the module's client cache.
type RemoteTables struct {
	Person *client.TableHandle[Person]
}

// RemoteReducers provides typed methods to call each reducer in the module.
type RemoteReducers struct {
	conn *client.DbConnection
}

// Add calls the Add reducer.
func (r *RemoteReducers) Add(name string) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteString(name)
	return r.conn.CallReducer("Add", w.Bytes())
}

// SayHello calls the SayHello reducer.
func (r *RemoteReducers) SayHello() (uint32, error) {
	return r.conn.CallReducer("SayHello", nil)
}

// RegisterTables registers all table handlers with the connection.
// Call this before conn.RunAsync.
func RegisterTables(conn *client.DbConnection, tables *RemoteTables) {
	conn.RegisterTableHandler("person", tables.Person)
}

// NewRemoteTables creates table handles for all module tables.
func NewRemoteTables() *RemoteTables {
	return &RemoteTables{
		Person: client.NewTableHandle[Person](ReadPerson),
	}
}

// NewRemoteReducers creates a RemoteReducers bound to the given connection.
func NewRemoteReducers(conn *client.DbConnection) *RemoteReducers {
	return &RemoteReducers{conn: conn}
}
