// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
//
// Run: spacetime generate --lang go --out-dir module_bindings

package module_bindings

import (
	"github.com/clockworklabs/spacetimedb-go/bsatn"
)

// Person is a row in the "Person" table.
type Person struct {
	Name string
}

func (p *Person) WriteBsatn(w *bsatn.Writer) {
	w.WriteString(p.Name)
}

func ReadPerson(r *bsatn.Reader) (Person, error) {
	name, err := r.ReadString()
	if err != nil {
		return Person{}, err
	}
	return Person{Name: name}, nil
}
