// stdbgen generates SpacetimeDB module registration code from a YAML schema.
//
// Usage:
//
//	stdbgen [-schema stdb.yaml] [-out generated_stdb.go] [-pkg main]
//
// Place a schema file in your module directory (default: stdb.yaml) and run:
//
//	go run github.com/clockworklabs/spacetimedb-go-server/cmd/stdbgen
//
// Or add the following to your main.go:
//
//	//go:generate go run github.com/clockworklabs/spacetimedb-go-server/cmd/stdbgen
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// ── Schema types ──────────────────────────────────────────────────────────────

// Schema is the top-level schema definition loaded from stdb.yaml.
type Schema struct {
	Package  string    `yaml:"package"`
	Module   string    `yaml:"module"`
	Tables   []Table   `yaml:"tables"`
	Reducers []Reducer `yaml:"reducers"`
}

// Table describes a SpacetimeDB table.
type Table struct {
	Name       string   `yaml:"name"`
	Columns    []Column `yaml:"columns"`
	PrimaryKey []string `yaml:"primary_key"`
	Access     string   `yaml:"access"` // "public" or "private" (default: "public")
	IsEvent    bool     `yaml:"is_event"`
}

// Column describes a single column of a table (or reducer parameter).
type Column struct {
	Name string `yaml:"name"`
	Type string `yaml:"type"` // Go type name: String, U8, U32, U64, I32, I64, Bool, F32, F64, Bytes
}

// Reducer describes a SpacetimeDB reducer.
type Reducer struct {
	Name       string   `yaml:"name"`
	Params     []Column `yaml:"params"`
	Visibility string   `yaml:"visibility"` // "public" or "private" (default: "public")
}

// ── Type mapping ──────────────────────────────────────────────────────────────

var typeMap = map[string]string{
	"String": "types.AlgebraicString",
	"Bool":   "types.AlgebraicBool",
	"I8":     "types.AlgebraicI8",
	"U8":     "types.AlgebraicU8",
	"I16":    "types.AlgebraicI16",
	"U16":    "types.AlgebraicU16",
	"I32":    "types.AlgebraicI32",
	"U32":    "types.AlgebraicU32",
	"I64":    "types.AlgebraicI64",
	"U64":    "types.AlgebraicU64",
	"I128":   "types.AlgebraicI128",
	"U128":   "types.AlgebraicU128",
	"F32":    "types.AlgebraicF32",
	"F64":    "types.AlgebraicF64",
	"Bytes":  "types.AlgebraicBytes",
}

// goReadType returns the bsatn.Reader method call for a column type.
var readMethod = map[string]string{
	"String": "r.ReadString()",
	"Bool":   "r.ReadBool()",
	"I8":     "r.ReadI8()",
	"U8":     "r.ReadU8()",
	"I16":    "r.ReadI16()",
	"U16":    "r.ReadU16()",
	"I32":    "r.ReadI32()",
	"U32":    "r.ReadU32()",
	"I64":    "r.ReadI64()",
	"U64":    "r.ReadU64()",
	"F32":    "r.ReadF32()",
	"F64":    "r.ReadF64()",
	"Bytes":  "r.ReadBytes()",
}

var goType = map[string]string{
	"String": "string",
	"Bool":   "bool",
	"I8":     "int8",
	"U8":     "uint8",
	"I16":    "int16",
	"U16":    "uint16",
	"I32":    "int32",
	"U32":    "uint32",
	"I64":    "int64",
	"U64":    "uint64",
	"F32":    "float32",
	"F64":    "float64",
	"Bytes":  "[]byte",
}

var writeMethod = map[string]string{
	"String": "w.WriteString",
	"Bool":   "w.WriteBool",
	"I8":     "w.WriteI8",
	"U8":     "w.WriteU8",
	"I16":    "w.WriteI16",
	"U16":    "w.WriteU16",
	"I32":    "w.WriteI32",
	"U32":    "w.WriteU32",
	"I64":    "w.WriteI64",
	"U64":    "w.WriteU64",
	"F32":    "w.WriteF32",
	"F64":    "w.WriteF64",
	"Bytes":  "w.WriteBytes",
}

// ── Template ─────────────────────────────────────────────────────────────────

const codeTmpl = `// Code generated by stdbgen. DO NOT EDIT.
// Source: {{.SchemaFile}}

package {{.Package}}

import (
	spacetimedb "github.com/clockworklabs/spacetimedb-go-server"
	"github.com/clockworklabs/spacetimedb-go/bsatn"
	"github.com/clockworklabs/spacetimedb-go/types"
	"github.com/clockworklabs/spacetimedb-go-server/sys"
)

// Ensure imports are used even if generated encode/decode functions don't reference all of them.
var _ = types.AlgebraicString
var _ = bsatn.NewWriter
var _ *sys.BytesSource

{{range .Tables}}{{$tname := .Name}}
// ── {{$tname}} table ──────────────────────────────────────────────────────────

// {{$tname}} is a row in the {{$tname}} table.
type {{$tname}} struct {
{{- range .Columns}}
	{{title .Name}} {{goType .Type}}
{{- end}}
}

func encode{{$tname}}(w *bsatn.Writer, row {{$tname}}) {
{{- range .Columns}}
	{{writeMethod .Type}}(row.{{title .Name}})
{{- end}}
}

func decode{{$tname}}(r *bsatn.Reader) ({{$tname}}, error) {
	var row {{$tname}}
	var err error
{{- range .Columns}}
	row.{{title .Name}}, err = {{readMethod .Type}}
	if err != nil {
		return {{$tname}}{}, err
	}
{{- end}}
	return row, nil
}

var {{lower $tname}}Table = spacetimedb.NewTableHandle("{{$tname}}", encode{{$tname}}, decode{{$tname}})
{{end}}

func init() {
{{range .Tables}}{{$tname := .Name}}
	// Register table: {{$tname}}
	spacetimedb.RegisterTableDef(spacetimedb.TableDef{
		Name: "{{$tname}}",
		Columns: []spacetimedb.ColumnDef{
{{- range .Columns}}
			{Name: "{{.Name}}", Type: {{algebraicType .Type}}},
{{- end}}
		},
		Access: {{tableAccess .Access}},
		IsEvent: {{.IsEvent}},
	})
{{end}}
{{range .Reducers}}{{$rname := .Name}}
	// Register reducer: {{$rname}}
	spacetimedb.RegisterReducerDef(spacetimedb.ReducerDef{
		Name: "{{$rname}}",
		Params: []spacetimedb.ColumnDef{
{{- range .Params}}
			{Name: "{{.Name}}", Type: {{algebraicType .Type}}},
{{- end}}
		},
		Visibility: {{reducerVisibility .Visibility}},
	})
	spacetimedb.RegisterReducerHandler(handle{{$rname}})
{{end}}
}
{{range .Reducers}}{{$rname := .Name}}
// handle{{$rname}} is the generated reducer handler skeleton for {{$rname}}.
// Replace this with your own implementation.
func handle{{$rname}}(ctx spacetimedb.ReducerContext, args sys.BytesSource) {
{{- if .Params}}
	data, err := sys.ReadBytesSource(args)
	if err != nil {
		spacetimedb.LogError("{{$rname}}: failed to read args: " + err.Error())
		return
	}
	r := bsatn.NewReader(data)
{{- range .Params}}
	{{lower .Name}}, err := {{readMethod .Type}}
	if err != nil {
		spacetimedb.LogError("{{$rname}}: failed to decode {{.Name}}: " + err.Error())
		return
	}
	_ = {{lower .Name}}
{{- end}}
{{- end}}
	// TODO: implement {{$rname}}
	_ = ctx
}
{{end}}
`

// ── Template helpers ──────────────────────────────────────────────────────────

func titleCase(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func lowerCase(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func tableAccess(access string) string {
	if strings.ToLower(access) == "private" {
		return "spacetimedb.TableAccessPrivate"
	}
	return "spacetimedb.TableAccessPublic"
}

func reducerVisibility(vis string) string {
	if strings.ToLower(vis) == "private" {
		return "spacetimedb.ReducerVisibilityPrivate"
	}
	return "spacetimedb.ReducerVisibilityClientCallable"
}

func algebraicType(t string) string {
	if v, ok := typeMap[t]; ok {
		return v
	}
	return "types.AlgebraicString" // fallback
}

func goTypeOf(t string) string {
	if v, ok := goType[t]; ok {
		return v
	}
	return "string" // fallback
}

func readMethodOf(t string) string {
	if v, ok := readMethod[t]; ok {
		return v
	}
	return "r.ReadString()"
}

func writeMethodOf(t string) string {
	if v, ok := writeMethod[t]; ok {
		return v
	}
	return "w.WriteString"
}

// ── Main ──────────────────────────────────────────────────────────────────────

func main() {
	schemaFile := flag.String("schema", "stdb.yaml", "path to the schema YAML file")
	outFile := flag.String("out", "generated_stdb.go", "path to the output Go file")
	pkg := flag.String("pkg", "", "package name (defaults to value from schema or 'main')")
	flag.Parse()

	data, err := os.ReadFile(*schemaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "stdbgen: cannot read schema %s: %v\n", *schemaFile, err)
		os.Exit(1)
	}

	var schema Schema
	if err := yaml.Unmarshal(data, &schema); err != nil {
		fmt.Fprintf(os.Stderr, "stdbgen: cannot parse schema: %v\n", err)
		os.Exit(1)
	}

	if *pkg != "" {
		schema.Package = *pkg
	}
	if schema.Package == "" {
		schema.Package = "main"
	}

	funcMap := template.FuncMap{
		"title":             titleCase,
		"lower":             lowerCase,
		"tableAccess":       tableAccess,
		"reducerVisibility": reducerVisibility,
		"algebraicType":     algebraicType,
		"goType":            goTypeOf,
		"readMethod":        readMethodOf,
		"writeMethod":       writeMethodOf,
	}

	tmpl, err := template.New("stdb").Funcs(funcMap).Parse(codeTmpl)
	if err != nil {
		fmt.Fprintf(os.Stderr, "stdbgen: template parse error: %v\n", err)
		os.Exit(1)
	}

	type tmplData struct {
		Schema
		SchemaFile string
	}
	d := tmplData{Schema: schema, SchemaFile: *schemaFile}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, d); err != nil {
		fmt.Fprintf(os.Stderr, "stdbgen: template execute error: %v\n", err)
		os.Exit(1)
	}

	// Format the generated code.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted so the user can see what went wrong.
		_ = os.WriteFile(*outFile, buf.Bytes(), 0644)
		fmt.Fprintf(os.Stderr, "stdbgen: gofmt error (raw output written): %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "stdbgen: cannot write %s: %v\n", *outFile, err)
		os.Exit(1)
	}

	fmt.Printf("stdbgen: wrote %s\n", *outFile)
}
