package main

// testTmpl is the Go template for generating encode/decode round-trip tests.
// The generated test file uses only bsatn and types packages, which do not
// require TinyGo, but shares a package with the generated code that does.
// Therefore the test file carries a //go:build tinygo constraint.
const testTmpl = `// Code generated by stdbgen. DO NOT EDIT.
// Source: {{.SchemaFile}}

//go:build tinygo

package {{.Package}}

import (
	"testing"

	"github.com/clockworklabs/spacetimedb-go/bsatn"
)

{{range .Tables}}{{$tname := .Name}}
// Test{{$tname}}EncodeDecode verifies that encoding and decoding a {{$tname}} row
// produces an identical value (round-trip correctness).
func Test{{$tname}}EncodeDecode(t *testing.T) {
	original := {{$tname}}{
{{- range .Columns}}
		{{title .Name}}: {{zeroVal .Type}},
{{- end}}
	}

	w := bsatn.NewWriter()
	encode{{$tname}}(w, original)

	r := bsatn.NewReader(w.Bytes())
	decoded, err := decode{{$tname}}(r)
	if err != nil {
		t.Fatalf("decode{{$tname}} failed: %v", err)
	}

{{- range .Columns}}
{{- if eq .Type "Bytes"}}
	if len(original.{{title .Name}}) != len(decoded.{{title .Name}}) {
		t.Errorf("{{$tname}}.{{title .Name}}: length mismatch: got %d, want %d", len(decoded.{{title .Name}}), len(original.{{title .Name}}))
	}
{{- else if isOptionType .Type}}
	if original.{{title .Name}} != decoded.{{title .Name}} {
		t.Errorf("{{$tname}}.{{title .Name}}: got %v, want %v", decoded.{{title .Name}}, original.{{title .Name}})
	}
{{- else}}
	if original.{{title .Name}} != decoded.{{title .Name}} {
		t.Errorf("{{$tname}}.{{title .Name}}: got %v, want %v", decoded.{{title .Name}}, original.{{title .Name}})
	}
{{- end}}
{{- end}}
}
{{end}}
`
