package main

// ── Code template ─────────────────────────────────────────────────────────────

const codeTmpl = `// Code generated by stdbgen. DO NOT EDIT.
// Source: {{.SchemaFile}}

package {{.Package}}

import (
	"iter"
	spacetimedb "github.com/clockworklabs/spacetimedb-go-server"
	"github.com/clockworklabs/spacetimedb-go/bsatn"
	"github.com/clockworklabs/spacetimedb-go/types"
	"github.com/clockworklabs/spacetimedb-go-server/sys"
)

// Ensure imports are used even if generated encode/decode functions don't reference all of them.
var _ = types.AlgebraicString
var _ = bsatn.NewWriter
var _ *sys.BytesSource
var _ iter.Seq2[struct{}, error]

// algebraicIdentity is the SATS type for a SpacetimeDB Identity (U256 newtype).
var algebraicIdentity = types.ProductType{
	Elements: []types.ProductTypeElement{
		{Name: strPtr("__identity__"), Type: types.AlgebraicU256},
	},
}

func strPtr(s string) *string { return &s }

{{range .Tables}}{{$tname := .Name}}
// ── {{$tname}} table ──────────────────────────────────────────────────────────

// {{$tname}} is a row in the {{$tname}} table.
type {{$tname}} struct {
{{- range .Columns}}
	{{title .Name}} {{goType .Type}}
{{- end}}
}

func encode{{$tname}}(w *bsatn.Writer, row {{$tname}}) {
{{- range .Columns}}
	{{encodeCol .Type .Name}}
{{- end}}
}

func decode{{$tname}}(r *bsatn.Reader) ({{$tname}}, error) {
	var row {{$tname}}
	var err error
{{- range .Columns}}
	row.{{title .Name}}, err = {{readMethod .Type}}
	if err != nil {
		return {{$tname}}{}, err
	}
{{- end}}
	return row, nil
}

var {{lower $tname}}Table = spacetimedb.NewTableHandle("{{$tname}}", encode{{$tname}}, decode{{$tname}})

{{range .UniqueIndexes}}{{$idxCamel := camelTitle .Name}}{{$colCamel := camelCols .Columns}}
// {{lower $tname}}{{$idxCamel}}Idx is a unique index on {{$tname}} columns: {{join .Columns ", "}}
var {{lower $tname}}{{$idxCamel}}Idx = spacetimedb.NewUniqueIndex[{{$tname}}, {{idxKeyGoType $tname .Columns}}](
	"{{$tname}}",
	"{{.Name}}",
	{{idxKeyWrite $tname .Columns}},
	encode{{$tname}},
	decode{{$tname}},
)

// Find{{$tname}}By{{$colCamel}} returns the row with the given {{join .Columns "/"}} value, or nil if not found.
func Find{{$tname}}By{{$colCamel}}(col {{idxKeyGoType $tname .Columns}}) (*{{$tname}}, error) {
	return {{lower $tname}}{{$idxCamel}}Idx.Find(col)
}

// Delete{{$tname}}By{{$colCamel}} deletes the row with the given {{join .Columns "/"}} value.
func Delete{{$tname}}By{{$colCamel}}(col {{idxKeyGoType $tname .Columns}}) (bool, error) {
	return {{lower $tname}}{{$idxCamel}}Idx.Delete(col)
}

// Update{{$tname}}By{{$colCamel}} upserts row using the {{join .Columns "/"}} unique index.
func Update{{$tname}}By{{$colCamel}}(row {{$tname}}) ({{$tname}}, error) {
	return {{lower $tname}}{{$idxCamel}}Idx.Update(row)
}
{{end}}

{{range .BTreeIndexes}}{{$idxCamel := camelTitle .Name}}{{$colCamel := camelCols .Columns}}
// {{lower $tname}}{{$idxCamel}}BTreeIdx is a BTree index on {{$tname}} columns: {{join .Columns ", "}}
var {{lower $tname}}{{$idxCamel}}BTreeIdx = spacetimedb.NewBTreeIndex[{{$tname}}, {{idxKeyGoType $tname .Columns}}](
	"{{.Name}}",
	{{idxKeyWrite $tname .Columns}},
	decode{{$tname}},
)

// Filter{{$tname}}By{{$colCamel}} returns all rows where {{join .Columns "/"}} equals col.
func Filter{{$tname}}By{{$colCamel}}(col {{idxKeyGoType $tname .Columns}}) iter.Seq2[{{$tname}}, error] {
	return {{lower $tname}}{{$idxCamel}}BTreeIdx.Filter(col)
}

// Filter{{$tname}}By{{$colCamel}}Range returns all rows where {{join .Columns "/"}} falls within [lo, hi].
func Filter{{$tname}}By{{$colCamel}}Range(lo, hi spacetimedb.Bound[{{idxKeyGoType $tname .Columns}}]) iter.Seq2[{{$tname}}, error] {
	return {{lower $tname}}{{$idxCamel}}BTreeIdx.FilterRange(lo, hi)
}
{{end}}

{{end}}

{{range .PrefixFilters}}
// {{.FuncName}} queries {{.TableName}} using a composite BTree index.
// It matches {{len .PrefixCols}} exact prefix column(s) and ranges over the trailing column.
func {{.FuncName}}(
{{- range .PrefixCols}}
	{{lower .Name}} {{.GoType}},
{{- end}}
	lo, hi spacetimedb.Bound[{{.TrailingType}}]) iter.Seq2[{{.TableName}}, error] {
	w := bsatn.NewWriter()
{{- range .PrefixCols}}
	{{.EncodeStmt}}
{{- end}}
	encTrail := {{.TrailingEncodeExpr}}
	loBytes := spacetimedb.EncodeBound(lo, encTrail)
	hiBytes := spacetimedb.EncodeBound(hi, encTrail)
	return {{.IdxVarName}}.FilterPrefixedRaw(w.Bytes(), {{.NumPrefix}}, loBytes, hiBytes)
}
{{end}}

func init() {
{{range .Tables}}{{$tname := .Name}}
	// Register table: {{$tname}}
	spacetimedb.RegisterTableDef(spacetimedb.TableDef{
		Name: "{{$tname}}",
		Columns: []spacetimedb.ColumnDef{
{{- range .Columns}}
			{Name: "{{.Name}}", Type: {{algebraicType .Type}}},
{{- end}}
		},
{{- if .PrimaryKey}}
		PrimaryKey: []uint16{ {{pkColIDs $tname .PrimaryKey .Columns}} },
{{- end}}
{{- if or .UniqueIndexes .BTreeIndexes}}
		Indexes: []spacetimedb.IndexDef{
{{- range .UniqueIndexes}}
			{SourceName: strPtr("{{.Name}}"), Algorithm: spacetimedb.IndexAlgorithmBTree, Columns: []uint16{ {{colIDs $tname .Columns}} }},
{{- end}}
{{- range .BTreeIndexes}}
			{SourceName: strPtr("{{.Name}}"), Algorithm: spacetimedb.IndexAlgorithmBTree, Columns: []uint16{ {{colIDs $tname .Columns}} }},
{{- end}}
		},
{{- end}}
{{- if .UniqueIndexes}}
		Constraints: []spacetimedb.ConstraintDef{
{{- range .UniqueIndexes}}
			{SourceName: strPtr("{{.Name}}_constraint"), Columns: []uint16{ {{colIDs $tname .Columns}} }},
{{- end}}
		},
{{- end}}
		Access: {{tableAccess .Access}},
		IsEvent: {{.IsEvent}},
	})
{{end}}

{{range .Reducers}}{{$rname := .Name}}
	// Register reducer: {{$rname}}
	spacetimedb.RegisterReducerDef(spacetimedb.ReducerDef{
		Name: "{{$rname}}",
		Params: []spacetimedb.ColumnDef{
{{- range .Params}}
			{Name: "{{.Name}}", Type: {{algebraicType .Type}}},
{{- end}}
		},
		Visibility: {{reducerVisibility .Visibility}},
	})
	spacetimedb.RegisterReducerHandler(handle{{$rname}})
{{end}}

{{if .Lifecycle.OnInit}}
	// Register lifecycle: Init ({{.Lifecycle.OnInit}})
	spacetimedb.RegisterReducerDef(spacetimedb.ReducerDef{
		Name:       "{{.Lifecycle.OnInit}}",
		Params:     []spacetimedb.ColumnDef{},
		Visibility: spacetimedb.ReducerVisibilityPrivate,
	})
	spacetimedb.RegisterReducerHandler(handle{{.Lifecycle.OnInit}})
	spacetimedb.RegisterLifecycleDef(spacetimedb.LifecycleDef{
		Kind:    spacetimedb.LifecycleInit,
		Reducer: "{{.Lifecycle.OnInit}}",
	})
{{end}}
{{if .Lifecycle.OnConnect}}
	// Register lifecycle: OnConnect ({{.Lifecycle.OnConnect}})
	spacetimedb.RegisterReducerDef(spacetimedb.ReducerDef{
		Name:       "{{.Lifecycle.OnConnect}}",
		Params:     []spacetimedb.ColumnDef{},
		Visibility: spacetimedb.ReducerVisibilityPrivate,
	})
	spacetimedb.RegisterReducerHandler(handle{{.Lifecycle.OnConnect}})
	spacetimedb.RegisterLifecycleDef(spacetimedb.LifecycleDef{
		Kind:    spacetimedb.LifecycleOnConnect,
		Reducer: "{{.Lifecycle.OnConnect}}",
	})
{{end}}
{{if .Lifecycle.OnDisconnect}}
	// Register lifecycle: OnDisconnect ({{.Lifecycle.OnDisconnect}})
	spacetimedb.RegisterReducerDef(spacetimedb.ReducerDef{
		Name:       "{{.Lifecycle.OnDisconnect}}",
		Params:     []spacetimedb.ColumnDef{},
		Visibility: spacetimedb.ReducerVisibilityPrivate,
	})
	spacetimedb.RegisterReducerHandler(handle{{.Lifecycle.OnDisconnect}})
	spacetimedb.RegisterLifecycleDef(spacetimedb.LifecycleDef{
		Kind:    spacetimedb.LifecycleOnDisconnect,
		Reducer: "{{.Lifecycle.OnDisconnect}}",
	})
{{end}}

{{range .Procedures}}{{$pname := .Name}}
	// Register procedure: {{$pname}}
	spacetimedb.RegisterProcedureDef(spacetimedb.ProcedureDef{
		Name: "{{$pname}}",
		Params: []spacetimedb.ColumnDef{
{{- range .Params}}
			{Name: "{{.Name}}", Type: {{algebraicType .Type}}},
{{- end}}
		},
		Visibility: {{reducerVisibility .Visibility}},
	})
	spacetimedb.RegisterProcedureHandler(handle{{$pname}}Procedure)
{{end}}

{{range .Views}}{{$vname := .Name}}
	// Register view: {{$vname}}
	spacetimedb.RegisterViewDef(spacetimedb.ViewDef{
		Name: "{{$vname}}",
		Params: []spacetimedb.ColumnDef{
{{- range .Params}}
			{Name: "{{.Name}}", Type: {{algebraicType .Type}}},
{{- end}}
		},
		IsPublic:    {{.IsPublic}},
		IsAnonymous: {{.IsAnonymous}},
	})
{{- if .IsAnonymous}}
	spacetimedb.RegisterViewAnonHandler(handle{{$vname}}ViewAnon)
{{- else}}
	spacetimedb.RegisterViewHandler(handle{{$vname}}View)
{{- end}}
{{end}}

	// Register named type exports for client code generation.
	// TypeRef indices 0..len(tables)-1 point to the table row ProductTypes in the typespace.
{{range $i, $t := .Tables}}
	spacetimedb.RegisterTypeDef(spacetimedb.TypeDef{
		Name:    "{{$t.Name}}",
		TypeRef: {{$i}},
	})
{{end}}

{{range $i, $t := .Types}}
	// Custom type: {{$t.Name}} (typespace index = {{add (len $.Tables) $i}})
	_ = spacetimedb.RegisterTypespaceType({{customAlgebraicType $t}})
	spacetimedb.RegisterTypeDef(spacetimedb.TypeDef{
		Name:    "{{$t.Name}}",
		TypeRef: {{add (len $.Tables) $i}},
	})
{{end}}

}

{{range .Reducers}}{{$rname := .Name}}
// handle{{$rname}} is the generated reducer handler skeleton for {{$rname}}.
// Replace this with your own implementation.
func handle{{$rname}}(ctx spacetimedb.ReducerContext, args sys.BytesSource) {
{{- if .Params}}
	data, err := sys.ReadBytesSource(args)
	if err != nil {
		panic("{{$rname}}: failed to read args: " + err.Error())
	}
	r := bsatn.NewReader(data)
{{- range .Params}}
	{{lower .Name}}, err := {{readMethod .Type}}
	if err != nil {
		panic("{{$rname}}: failed to decode {{.Name}}: " + err.Error())
	}
	_ = {{lower .Name}}
{{- end}}
{{- end}}
	// TODO: implement {{$rname}}
	_ = ctx
}
{{end}}

{{if .Lifecycle.OnInit}}
// handle{{.Lifecycle.OnInit}} is the generated Init lifecycle handler.
func handle{{.Lifecycle.OnInit}}(ctx spacetimedb.ReducerContext, _ sys.BytesSource) {
	// TODO: implement module initialization
	_ = ctx
}
{{end}}
{{if .Lifecycle.OnConnect}}
// handle{{.Lifecycle.OnConnect}} is the generated OnConnect lifecycle handler.
func handle{{.Lifecycle.OnConnect}}(ctx spacetimedb.ReducerContext, _ sys.BytesSource) {
	// TODO: handle client connect for ctx.Sender
	_ = ctx
}
{{end}}
{{if .Lifecycle.OnDisconnect}}
// handle{{.Lifecycle.OnDisconnect}} is the generated OnDisconnect lifecycle handler.
func handle{{.Lifecycle.OnDisconnect}}(ctx spacetimedb.ReducerContext, _ sys.BytesSource) {
	// TODO: handle client disconnect for ctx.Sender
	_ = ctx
}
{{end}}

{{range .Procedures}}{{$pname := .Name}}
// handle{{$pname}}Procedure is the generated procedure handler skeleton for {{$pname}}.
func handle{{$pname}}Procedure(ctx spacetimedb.ProcedureContext, args sys.BytesSource, result sys.BytesSink) {
{{- if .Params}}
	data, err := sys.ReadBytesSource(args)
	if err != nil {
		panic("{{$pname}}: failed to read args: " + err.Error())
	}
	r := bsatn.NewReader(data)
{{- range .Params}}
	{{lower .Name}}, err := {{readMethod .Type}}
	if err != nil {
		panic("{{$pname}}: failed to decode {{.Name}}: " + err.Error())
	}
	_ = {{lower .Name}}
{{- end}}
{{- end}}
	// TODO: implement {{$pname}}
	_ = ctx
	_ = result
}
{{end}}

{{range .Views}}{{$vname := .Name}}
{{- if .IsAnonymous}}
// handle{{$vname}}ViewAnon is the generated anonymous view handler skeleton for {{$vname}}.
func handle{{$vname}}ViewAnon(args sys.BytesSource, rows sys.BytesSink) {
	// TODO: implement {{$vname}} view; write BSATN-encoded rows to rows
	_ = args
	_ = rows
}
{{- else}}
// handle{{$vname}}View is the generated authenticated view handler skeleton for {{$vname}}.
func handle{{$vname}}View(sender types.Identity, connectionId *types.ConnectionId, args sys.BytesSource, rows sys.BytesSink) {
	// TODO: implement {{$vname}} view; write BSATN-encoded rows to rows
	_ = sender
	_ = connectionId
	_ = args
	_ = rows
}
{{- end}}
{{end}}
`
