// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

import (
	"context"
	"errors"
	"github.com/SMG3zx/SpacetimeDB/sdks/go/connection"
)

type Result[T any, E any] struct {
	Ok  *T
	Err *E
}

type ScheduleAt struct {
	Tag   string `json:"tag"`
	Value any    `json:"value,omitempty"`
}

type Client struct {
	conn *connection.Connection
}

func NewClient(conn *connection.Connection) *Client {
	return &Client{conn: conn}
}

func (c *Client) Connection() *connection.Connection { return c.conn }

func (c *Client) CallReducer(ctx context.Context, reducer string, args []byte, callback connection.ReducerResultCallback) (uint32, error) {
	if c == nil || c.conn == nil {
		return 0, errors.New("spacetimedb client is not connected")
	}
	if ctx != nil {
		select {
		case <-ctx.Done():
			return 0, ctx.Err()
		default:
		}
	}
	return c.conn.CallReducer(reducer, args, callback)
}

func (c *Client) CallProcedure(ctx context.Context, procedure string, args []byte, callback connection.ProcedureResultCallback) (uint32, error) {
	if c == nil || c.conn == nil {
		return 0, errors.New("spacetimedb client is not connected")
	}
	if ctx != nil {
		select {
		case <-ctx.Done():
			return 0, ctx.Err()
		default:
		}
	}
	return c.conn.CallProcedure(procedure, args, callback)
}

func (c *Client) OneOffQuery(ctx context.Context, query string, callback connection.OneOffQueryResultCallback) (uint32, error) {
	if c == nil || c.conn == nil {
		return 0, errors.New("spacetimedb client is not connected")
	}
	if ctx != nil {
		select {
		case <-ctx.Done():
			return 0, ctx.Err()
		default:
		}
	}
	return c.conn.OneOffQuery(query, callback)
}
