// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type ReducerOutcomeTag string

const (
	ReducerOutcomeTagOk            ReducerOutcomeTag = "Ok"
	ReducerOutcomeTagOkEmpty       ReducerOutcomeTag = "OkEmpty"
	ReducerOutcomeTagErr           ReducerOutcomeTag = "Err"
	ReducerOutcomeTagInternalError ReducerOutcomeTag = "InternalError"
)

type ReducerOutcome struct {
	Tag   ReducerOutcomeTag `json:"tag"`
	Value any               `json:"value,omitempty"`
}
