// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

import (
	"time"
)

type ProcedureResult struct {
	Status                     ProcedureStatus `json:"status"`
	Timestamp                  time.Time       `json:"timestamp"`
	TotalHostExecutionDuration time.Duration   `json:"total_host_execution_duration"`
	RequestId                  uint32          `json:"request_id"`
}
