// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type ServerMessageTag string

const (
	ServerMessageTagInitialConnection  ServerMessageTag = "InitialConnection"
	ServerMessageTagSubscribeApplied   ServerMessageTag = "SubscribeApplied"
	ServerMessageTagUnsubscribeApplied ServerMessageTag = "UnsubscribeApplied"
	ServerMessageTagSubscriptionError  ServerMessageTag = "SubscriptionError"
	ServerMessageTagTransactionUpdate  ServerMessageTag = "TransactionUpdate"
	ServerMessageTagOneOffQueryResult  ServerMessageTag = "OneOffQueryResult"
	ServerMessageTagReducerResult      ServerMessageTag = "ReducerResult"
	ServerMessageTagProcedureResult    ServerMessageTag = "ProcedureResult"
)

type ServerMessage struct {
	Tag   ServerMessageTag `json:"tag"`
	Value any              `json:"value,omitempty"`
}
