// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type PersistentTableRows struct {
	Inserts BsatnRowList `json:"inserts"`
	Deletes BsatnRowList `json:"deletes"`
}
