// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type TableUpdateRowsTag string

const (
	TableUpdateRowsTagPersistentTable TableUpdateRowsTag = "PersistentTable"
	TableUpdateRowsTagEventTable      TableUpdateRowsTag = "EventTable"
)

type TableUpdateRows struct {
	Tag   TableUpdateRowsTag `json:"tag"`
	Value any                `json:"value,omitempty"`
}
