// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type CallReducer struct {
	RequestId uint32  `json:"request_id"`
	Flags     uint8   `json:"flags"`
	Reducer   string  `json:"reducer"`
	Args      []uint8 `json:"args"`
}
