// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

import (
	"time"
)

type ReducerResult struct {
	RequestId uint32         `json:"request_id"`
	Timestamp time.Time      `json:"timestamp"`
	Result    ReducerOutcome `json:"result"`
}
