// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type TableUpdate struct {
	TableName string            `json:"table_name"`
	Rows      []TableUpdateRows `json:"rows"`
}
