// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type ProcedureStatusTag string

const (
	ProcedureStatusTagReturned      ProcedureStatusTag = "Returned"
	ProcedureStatusTagInternalError ProcedureStatusTag = "InternalError"
)

type ProcedureStatus struct {
	Tag   ProcedureStatusTag `json:"tag"`
	Value any                `json:"value,omitempty"`
}
