// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type OneOffQueryResult struct {
	RequestId uint32                    `json:"request_id"`
	Result    Result[QueryRows, string] `json:"result"`
}
