// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type InitialConnection struct {
	Identity     string `json:"identity"`
	ConnectionId string `json:"connection_id"`
	Token        string `json:"token"`
}
