// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type ReducerOk struct {
	RetValue          []uint8           `json:"ret_value"`
	TransactionUpdate TransactionUpdate `json:"transaction_update"`
}
