// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type RowSizeHintTag string

const (
	RowSizeHintTagFixedSize  RowSizeHintTag = "FixedSize"
	RowSizeHintTagRowOffsets RowSizeHintTag = "RowOffsets"
)

type RowSizeHint struct {
	Tag   RowSizeHintTag `json:"tag"`
	Value any            `json:"value,omitempty"`
}
