// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type ClientMessageTag string

const (
	ClientMessageTagSubscribe     ClientMessageTag = "Subscribe"
	ClientMessageTagUnsubscribe   ClientMessageTag = "Unsubscribe"
	ClientMessageTagOneOffQuery   ClientMessageTag = "OneOffQuery"
	ClientMessageTagCallReducer   ClientMessageTag = "CallReducer"
	ClientMessageTagCallProcedure ClientMessageTag = "CallProcedure"
)

type ClientMessage struct {
	Tag   ClientMessageTag `json:"tag"`
	Value any              `json:"value,omitempty"`
}
