// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type UnsubscribeFlags uint8

const (
	UnsubscribeFlagsDefault UnsubscribeFlags = iota
	UnsubscribeFlagsSendDroppedRows
)
