// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type Unsubscribe struct {
	RequestId  uint32           `json:"request_id"`
	QuerySetId QuerySetId       `json:"query_set_id"`
	Flags      UnsubscribeFlags `json:"flags"`
}
