// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type BsatnRowList struct {
	SizeHint RowSizeHint `json:"size_hint"`
	RowsData []uint8     `json:"rows_data"`
}
