// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

package clientapi

type QuerySetUpdate struct {
	QuerySetId QuerySetId    `json:"query_set_id"`
	Tables     []TableUpdate `json:"tables"`
}
