// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
//
// Run: spacetime generate --lang go --out-dir module_bindings

package module_bindings

import (
	"github.com/clockworklabs/spacetimedb-go/bsatn"
	"github.com/clockworklabs/spacetimedb-go/client"
)

// RemoteTables provides typed access to all tables in the module's client cache.
type RemoteTables struct {
	Message *client.TableHandle[Message]
	User    *client.TableHandle[User]
}

// RemoteReducers provides typed methods to call each reducer in the module.
type RemoteReducers struct {
	conn *client.DbConnection
}

// SendMessage calls the send_message reducer.
func (r *RemoteReducers) SendMessage(text string) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteString(text)
	return r.conn.CallReducer("send_message", w.Bytes())
}

// SetName calls the set_name reducer.
func (r *RemoteReducers) SetName(name string) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteString(name)
	return r.conn.CallReducer("set_name", w.Bytes())
}

// RegisterTables registers all table handlers with the connection.
// Call this before conn.RunAsync.
func RegisterTables(conn *client.DbConnection, tables *RemoteTables) {
	conn.RegisterTableHandler("message", tables.Message)
	conn.RegisterTableHandler("user", tables.User)
}

// NewRemoteTables creates table handles for all module tables.
func NewRemoteTables() *RemoteTables {
	return &RemoteTables{
		Message: client.NewTableHandle[Message](ReadMessage),
		User:    client.NewTableHandle[User](ReadUser),
	}
}

// NewRemoteReducers creates a RemoteReducers bound to the given connection.
func NewRemoteReducers(conn *client.DbConnection) *RemoteReducers {
	return &RemoteReducers{conn: conn}
}
