// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
//
// Run: spacetime generate --lang go --out-dir module_bindings

package module_bindings

import (
	"github.com/clockworklabs/spacetimedb-go/bsatn"
	"github.com/clockworklabs/spacetimedb-go/types"
)

// Message is a row in the "message" table.
type Message struct {
	Sender types.Identity
	Sent   types.Timestamp
	Text   string
}

func (m *Message) WriteBsatn(w *bsatn.Writer) {
	m.Sender.WriteBsatn(w)
	m.Sent.WriteBsatn(w)
	w.WriteString(m.Text)
}

func ReadMessage(r *bsatn.Reader) (Message, error) {
	sender, err := types.ReadIdentity(r)
	if err != nil {
		return Message{}, err
	}
	sent, err := types.ReadTimestamp(r)
	if err != nil {
		return Message{}, err
	}
	text, err := r.ReadString()
	if err != nil {
		return Message{}, err
	}
	return Message{Sender: sender, Sent: sent, Text: text}, nil
}

// User is a row in the "user" table.
type User struct {
	Identity types.Identity
	Name     *string
	Online   bool
}

func (u *User) WriteBsatn(w *bsatn.Writer) {
	u.Identity.WriteBsatn(w)
	bsatn.WriteOption(w, u.Name, func(w *bsatn.Writer, s string) { w.WriteString(s) })
	w.WriteBool(u.Online)
}

func ReadUser(r *bsatn.Reader) (User, error) {
	identity, err := types.ReadIdentity(r)
	if err != nil {
		return User{}, err
	}
	name, err := bsatn.ReadOption(r, func(r *bsatn.Reader) (string, error) { return r.ReadString() })
	if err != nil {
		return User{}, err
	}
	online, err := r.ReadBool()
	if err != nil {
		return User{}, err
	}
	return User{Identity: identity, Name: name, Online: online}, nil
}
