// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
//
// Run: spacetime generate --lang go --out-dir module_bindings

package module_bindings

import (
	"github.com/clockworklabs/spacetimedb-go/bsatn"
	"github.com/clockworklabs/spacetimedb-go/client"
)

// RemoteTables provides typed access to all tables in the module's client cache.
type RemoteTables struct {
	OneU8         *client.TableHandle[OneU8]
	OneU32        *client.TableHandle[OneU32]
	OneU64        *client.TableHandle[OneU64]
	OneString     *client.TableHandle[OneString]
	OneBool       *client.TableHandle[OneBool]
	OneIdentity   *client.TableHandle[OneIdentity]
	OneTimestamp  *client.TableHandle[OneTimestamp]
	OneSimpleEnum *client.TableHandle[OneSimpleEnum]
	VecU32        *client.TableHandle[VecU32]
	VecString     *client.TableHandle[VecString]
	OptionI32     *client.TableHandle[OptionI32]
	OptionString  *client.TableHandle[OptionString]
	PkU32         *client.TableHandle[PkU32]
	UniqueU32     *client.TableHandle[UniqueU32]
}

// RemoteReducers provides typed methods to call each reducer in the module.
type RemoteReducers struct {
	conn *client.DbConnection
}

// InsertOneU8 calls the insert_one_u8 reducer.
func (r *RemoteReducers) InsertOneU8(n uint8) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU8(n)
	return r.conn.CallReducer("insert_one_u8", w.Bytes())
}

// InsertOneU32 calls the insert_one_u32 reducer.
func (r *RemoteReducers) InsertOneU32(n uint32) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU32(n)
	return r.conn.CallReducer("insert_one_u32", w.Bytes())
}

// InsertOneU64 calls the insert_one_u64 reducer.
func (r *RemoteReducers) InsertOneU64(n uint64) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU64(n)
	return r.conn.CallReducer("insert_one_u64", w.Bytes())
}

// InsertOneString calls the insert_one_string reducer.
func (r *RemoteReducers) InsertOneString(s string) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteString(s)
	return r.conn.CallReducer("insert_one_string", w.Bytes())
}

// InsertOneBool calls the insert_one_bool reducer.
func (r *RemoteReducers) InsertOneBool(b bool) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteBool(b)
	return r.conn.CallReducer("insert_one_bool", w.Bytes())
}

// InsertOneSimpleEnum calls the insert_one_simple_enum reducer.
func (r *RemoteReducers) InsertOneSimpleEnum(e SimpleEnum) (uint32, error) {
	w := bsatn.NewWriter()
	e.WriteBsatn(w)
	return r.conn.CallReducer("insert_one_simple_enum", w.Bytes())
}

// InsertVecU32 calls the insert_vec_u32 reducer.
func (r *RemoteReducers) InsertVecU32(n []uint32) (uint32, error) {
	w := bsatn.NewWriter()
	bsatn.WriteSlice(w, n, func(w *bsatn.Writer, v uint32) { w.WriteU32(v) })
	return r.conn.CallReducer("insert_vec_u32", w.Bytes())
}

// InsertVecString calls the insert_vec_string reducer.
func (r *RemoteReducers) InsertVecString(s []string) (uint32, error) {
	w := bsatn.NewWriter()
	bsatn.WriteSlice(w, s, func(w *bsatn.Writer, v string) { w.WriteString(v) })
	return r.conn.CallReducer("insert_vec_string", w.Bytes())
}

// InsertOptionI32 calls the insert_option_i32 reducer.
func (r *RemoteReducers) InsertOptionI32(n *int32) (uint32, error) {
	w := bsatn.NewWriter()
	bsatn.WriteOption(w, n, func(w *bsatn.Writer, v int32) { w.WriteI32(v) })
	return r.conn.CallReducer("insert_option_i32", w.Bytes())
}

// InsertOptionString calls the insert_option_string reducer.
func (r *RemoteReducers) InsertOptionString(s *string) (uint32, error) {
	w := bsatn.NewWriter()
	bsatn.WriteOption(w, s, func(w *bsatn.Writer, v string) { w.WriteString(v) })
	return r.conn.CallReducer("insert_option_string", w.Bytes())
}

// InsertPkU32 calls the insert_pk_u32 reducer.
func (r *RemoteReducers) InsertPkU32(n uint32, data int32) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU32(n)
	w.WriteI32(data)
	return r.conn.CallReducer("insert_pk_u32", w.Bytes())
}

// UpdatePkU32 calls the update_pk_u32 reducer.
func (r *RemoteReducers) UpdatePkU32(n uint32, data int32) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU32(n)
	w.WriteI32(data)
	return r.conn.CallReducer("update_pk_u32", w.Bytes())
}

// DeletePkU32 calls the delete_pk_u32 reducer.
func (r *RemoteReducers) DeletePkU32(n uint32) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU32(n)
	return r.conn.CallReducer("delete_pk_u32", w.Bytes())
}

// InsertUniqueU32 calls the insert_unique_u32 reducer.
func (r *RemoteReducers) InsertUniqueU32(n uint32, data int32) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU32(n)
	w.WriteI32(data)
	return r.conn.CallReducer("insert_unique_u32", w.Bytes())
}

// UpdateUniqueU32 calls the update_unique_u32 reducer.
func (r *RemoteReducers) UpdateUniqueU32(n uint32, data int32) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU32(n)
	w.WriteI32(data)
	return r.conn.CallReducer("update_unique_u32", w.Bytes())
}

// DeleteUniqueU32 calls the delete_unique_u32 reducer.
func (r *RemoteReducers) DeleteUniqueU32(n uint32) (uint32, error) {
	w := bsatn.NewWriter()
	w.WriteU32(n)
	return r.conn.CallReducer("delete_unique_u32", w.Bytes())
}

// NoOpSucceeds calls the no_op_succeeds reducer.
func (r *RemoteReducers) NoOpSucceeds() (uint32, error) {
	return r.conn.CallReducer("no_op_succeeds", nil)
}

// RegisterTables registers all table handlers with the connection.
// Call this before conn.RunAsync.
func RegisterTables(conn *client.DbConnection, tables *RemoteTables) {
	conn.RegisterTableHandler("one_u_8", tables.OneU8)
	conn.RegisterTableHandler("one_u_32", tables.OneU32)
	conn.RegisterTableHandler("one_u_64", tables.OneU64)
	conn.RegisterTableHandler("one_string", tables.OneString)
	conn.RegisterTableHandler("one_bool", tables.OneBool)
	conn.RegisterTableHandler("one_identity", tables.OneIdentity)
	conn.RegisterTableHandler("one_timestamp", tables.OneTimestamp)
	conn.RegisterTableHandler("one_simple_enum", tables.OneSimpleEnum)
	conn.RegisterTableHandler("vec_u_32", tables.VecU32)
	conn.RegisterTableHandler("vec_string", tables.VecString)
	conn.RegisterTableHandler("option_i_32", tables.OptionI32)
	conn.RegisterTableHandler("option_string", tables.OptionString)
	conn.RegisterTableHandler("pk_u_32", tables.PkU32)
	conn.RegisterTableHandler("unique_u_32", tables.UniqueU32)
}

// NewRemoteTables creates table handles for all module tables.
func NewRemoteTables() *RemoteTables {
	return &RemoteTables{
		OneU8:         client.NewTableHandle(ReadOneU8),
		OneU32:        client.NewTableHandle(ReadOneU32),
		OneU64:        client.NewTableHandle(ReadOneU64),
		OneString:     client.NewTableHandle(ReadOneString),
		OneBool:       client.NewTableHandle(ReadOneBool),
		OneIdentity:   client.NewTableHandle(ReadOneIdentity),
		OneTimestamp:  client.NewTableHandle(ReadOneTimestamp),
		OneSimpleEnum: client.NewTableHandle(ReadOneSimpleEnum),
		VecU32:        client.NewTableHandle(ReadVecU32),
		VecString:     client.NewTableHandle(ReadVecString),
		OptionI32:     client.NewTableHandle(ReadOptionI32),
		OptionString:  client.NewTableHandle(ReadOptionString),
		PkU32:         client.NewTableHandle(ReadPkU32),
		UniqueU32:     client.NewTableHandle(ReadUniqueU32),
	}
}

// NewRemoteReducers creates a RemoteReducers bound to the given connection.
func NewRemoteReducers(conn *client.DbConnection) *RemoteReducers {
	return &RemoteReducers{conn: conn}
}
