// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
//
// Run: spacetime generate --lang go --out-dir module_bindings

package module_bindings

import (
	"github.com/clockworklabs/spacetimedb-go/bsatn"
	"github.com/clockworklabs/spacetimedb-go/types"
)

// SimpleEnum matches the SimpleEnum in the sdk-test module.
type SimpleEnum uint8

const (
	SimpleEnumZero SimpleEnum = 0
	SimpleEnumOne  SimpleEnum = 1
	SimpleEnumTwo  SimpleEnum = 2
)

func (e SimpleEnum) WriteBsatn(w *bsatn.Writer) {
	w.WriteU8(uint8(e))
}

func ReadSimpleEnum(r *bsatn.Reader) (SimpleEnum, error) {
	v, err := r.ReadU8()
	return SimpleEnum(v), err
}

// OneU8 is a row in the "one_u_8" table.
type OneU8 struct {
	N uint8
}

func (r *OneU8) WriteBsatn(w *bsatn.Writer) {
	w.WriteU8(r.N)
}

func ReadOneU8(r *bsatn.Reader) (OneU8, error) {
	n, err := r.ReadU8()
	if err != nil {
		return OneU8{}, err
	}
	return OneU8{N: n}, nil
}

// OneU32 is a row in the "one_u_32" table.
type OneU32 struct {
	N uint32
}

func (r *OneU32) WriteBsatn(w *bsatn.Writer) {
	w.WriteU32(r.N)
}

func ReadOneU32(r *bsatn.Reader) (OneU32, error) {
	n, err := r.ReadU32()
	if err != nil {
		return OneU32{}, err
	}
	return OneU32{N: n}, nil
}

// OneU64 is a row in the "one_u_64" table.
type OneU64 struct {
	N uint64
}

func (r *OneU64) WriteBsatn(w *bsatn.Writer) {
	w.WriteU64(r.N)
}

func ReadOneU64(r *bsatn.Reader) (OneU64, error) {
	n, err := r.ReadU64()
	if err != nil {
		return OneU64{}, err
	}
	return OneU64{N: n}, nil
}

// OneString is a row in the "one_string" table.
type OneString struct {
	S string
}

func (r *OneString) WriteBsatn(w *bsatn.Writer) {
	w.WriteString(r.S)
}

func ReadOneString(r *bsatn.Reader) (OneString, error) {
	s, err := r.ReadString()
	if err != nil {
		return OneString{}, err
	}
	return OneString{S: s}, nil
}

// OneBool is a row in the "one_bool" table.
type OneBool struct {
	B bool
}

func (r *OneBool) WriteBsatn(w *bsatn.Writer) {
	w.WriteBool(r.B)
}

func ReadOneBool(r *bsatn.Reader) (OneBool, error) {
	b, err := r.ReadBool()
	if err != nil {
		return OneBool{}, err
	}
	return OneBool{B: b}, nil
}

// OneIdentity is a row in the "one_identity" table.
type OneIdentity struct {
	I types.Identity
}

func (r *OneIdentity) WriteBsatn(w *bsatn.Writer) {
	r.I.WriteBsatn(w)
}

func ReadOneIdentity(r *bsatn.Reader) (OneIdentity, error) {
	i, err := types.ReadIdentity(r)
	if err != nil {
		return OneIdentity{}, err
	}
	return OneIdentity{I: i}, nil
}

// OneTimestamp is a row in the "one_timestamp" table.
type OneTimestamp struct {
	T types.Timestamp
}

func (r *OneTimestamp) WriteBsatn(w *bsatn.Writer) {
	r.T.WriteBsatn(w)
}

func ReadOneTimestamp(r *bsatn.Reader) (OneTimestamp, error) {
	t, err := types.ReadTimestamp(r)
	if err != nil {
		return OneTimestamp{}, err
	}
	return OneTimestamp{T: t}, nil
}

// OneSimpleEnum is a row in the "one_simple_enum" table.
type OneSimpleEnum struct {
	E SimpleEnum
}

func (r *OneSimpleEnum) WriteBsatn(w *bsatn.Writer) {
	r.E.WriteBsatn(w)
}

func ReadOneSimpleEnum(r *bsatn.Reader) (OneSimpleEnum, error) {
	e, err := ReadSimpleEnum(r)
	if err != nil {
		return OneSimpleEnum{}, err
	}
	return OneSimpleEnum{E: e}, nil
}

// VecU32 is a row in the "vec_u_32" table.
type VecU32 struct {
	N []uint32
}

func (r *VecU32) WriteBsatn(w *bsatn.Writer) {
	bsatn.WriteSlice(w, r.N, func(w *bsatn.Writer, v uint32) { w.WriteU32(v) })
}

func ReadVecU32(r *bsatn.Reader) (VecU32, error) {
	n, err := bsatn.ReadSlice(r, func(r *bsatn.Reader) (uint32, error) { return r.ReadU32() })
	if err != nil {
		return VecU32{}, err
	}
	return VecU32{N: n}, nil
}

// VecString is a row in the "vec_string" table.
type VecString struct {
	S []string
}

func (r *VecString) WriteBsatn(w *bsatn.Writer) {
	bsatn.WriteSlice(w, r.S, func(w *bsatn.Writer, v string) { w.WriteString(v) })
}

func ReadVecString(r *bsatn.Reader) (VecString, error) {
	s, err := bsatn.ReadSlice(r, func(r *bsatn.Reader) (string, error) { return r.ReadString() })
	if err != nil {
		return VecString{}, err
	}
	return VecString{S: s}, nil
}

// OptionI32 is a row in the "option_i_32" table.
type OptionI32 struct {
	N *int32
}

func (r *OptionI32) WriteBsatn(w *bsatn.Writer) {
	bsatn.WriteOption(w, r.N, func(w *bsatn.Writer, v int32) { w.WriteI32(v) })
}

func ReadOptionI32(r *bsatn.Reader) (OptionI32, error) {
	n, err := bsatn.ReadOption(r, func(r *bsatn.Reader) (int32, error) { return r.ReadI32() })
	if err != nil {
		return OptionI32{}, err
	}
	return OptionI32{N: n}, nil
}

// OptionString is a row in the "option_string" table.
type OptionString struct {
	S *string
}

func (r *OptionString) WriteBsatn(w *bsatn.Writer) {
	bsatn.WriteOption(w, r.S, func(w *bsatn.Writer, v string) { w.WriteString(v) })
}

func ReadOptionString(r *bsatn.Reader) (OptionString, error) {
	s, err := bsatn.ReadOption(r, func(r *bsatn.Reader) (string, error) { return r.ReadString() })
	if err != nil {
		return OptionString{}, err
	}
	return OptionString{S: s}, nil
}

// PkU32 is a row in the "pk_u_32" table.
type PkU32 struct {
	N    uint32
	Data int32
}

func (r *PkU32) WriteBsatn(w *bsatn.Writer) {
	w.WriteU32(r.N)
	w.WriteI32(r.Data)
}

func ReadPkU32(r *bsatn.Reader) (PkU32, error) {
	n, err := r.ReadU32()
	if err != nil {
		return PkU32{}, err
	}
	data, err := r.ReadI32()
	if err != nil {
		return PkU32{}, err
	}
	return PkU32{N: n, Data: data}, nil
}

// UniqueU32 is a row in the "unique_u_32" table.
type UniqueU32 struct {
	N    uint32
	Data int32
}

func (r *UniqueU32) WriteBsatn(w *bsatn.Writer) {
	w.WriteU32(r.N)
	w.WriteI32(r.Data)
}

func ReadUniqueU32(r *bsatn.Reader) (UniqueU32, error) {
	n, err := r.ReadU32()
	if err != nil {
		return UniqueU32{}, err
	}
	data, err := r.ReadI32()
	if err != nil {
		return UniqueU32{}, err
	}
	return UniqueU32{N: n, Data: data}, nil
}
