//go:build tinygo

package spacetimedb

import "github.com/clockworklabs/spacetimedb-go/types"

// ── Module descriptor types ──────────────────────────────────────────────────

// ColumnDef describes a single column in a table.
type ColumnDef struct {
	Name string
	Type types.AlgebraicType
}

// TableAccess controls who can read the table.
type TableAccess uint8

const (
	TableAccessPublic  TableAccess = 0 // visible to all clients
	TableAccessPrivate TableAccess = 1 // visible only to the module owner
)

// IndexAlgorithm selects the index implementation.
type IndexAlgorithm uint8

const (
	IndexAlgorithmBTree  IndexAlgorithm = 0
	IndexAlgorithmHash   IndexAlgorithm = 1
	IndexAlgorithmDirect IndexAlgorithm = 2
)

// IndexDef describes a single index on a table.
type IndexDef struct {
	SourceName   *string // nil = auto-generated by host
	AccessorName *string // nil = no explicit accessor name
	Algorithm    IndexAlgorithm
	Columns      []uint16 // column positions (ColId); exactly 1 for Direct
}

// ConstraintDef describes a unique constraint on a table.
type ConstraintDef struct {
	SourceName *string
	Columns    []uint16
}

// SequenceDef describes an auto-increment sequence for a column.
type SequenceDef struct {
	SourceName *string
	Column     uint16
	Start      *int64 // nil = host chooses starting value; sign-extended to i128
	Increment  int64  // typically 1
}

// ColumnDefaultValue pairs a column ID with its BSATN-encoded default value.
type ColumnDefaultValue struct {
	ColId uint16
	Value []byte // BSATN-encoded default value
}

// TableDef describes a table to be registered in the module.
type TableDef struct {
	Name          string
	Columns       []ColumnDef
	PrimaryKey    []uint16 // ColId list; empty or length 1
	Indexes       []IndexDef
	Constraints   []ConstraintDef
	Sequences     []SequenceDef
	Access        TableAccess
	IsEvent       bool
	DefaultValues []ColumnDefaultValue
}

// ReducerVisibility controls who can invoke a reducer.
type ReducerVisibility uint8

const (
	ReducerVisibilityPrivate        ReducerVisibility = 0
	ReducerVisibilityClientCallable ReducerVisibility = 1
)

// ReducerDef describes a reducer to be registered in the module.
type ReducerDef struct {
	Name       string
	Params     []ColumnDef
	Visibility ReducerVisibility
}

// LifecycleKind identifies a module lifecycle event.
type LifecycleKind uint8

const (
	LifecycleInit          LifecycleKind = 0 // called on module initialization
	LifecycleOnConnect     LifecycleKind = 1 // called when a client connects
	LifecycleOnDisconnect  LifecycleKind = 2 // called when a client disconnects
)

// LifecycleDef assigns a reducer to a lifecycle event.
type LifecycleDef struct {
	Kind    LifecycleKind
	Reducer string
}

// TypeDef exports a named type to client code generation.
// The TypeRef must be a valid index into the module's typespace.
type TypeDef struct {
	// Scope is the namespace path (usually empty for top-level types).
	Scope []string
	// Name is the exported type name (must be unique within the module).
	Name string
	// TypeRef is the AlgebraicTypeRef index into the module typespace.
	TypeRef uint32
	// CustomOrdering controls whether the type has a custom field order.
	CustomOrdering bool
}

// CaseConversionPolicy controls how identifier names are converted to canonical form.
type CaseConversionPolicy uint8

const (
	// CaseConversionNone uses names verbatim with no conversion.
	CaseConversionNone CaseConversionPolicy = 0
	// CaseConversionSnakeCase converts names to snake_case (SpacetimeDB default).
	CaseConversionSnakeCase CaseConversionPolicy = 1
)

// NameMappingKind identifies the entity type for an explicit name mapping.
type NameMappingKind uint8

const (
	NameMappingTable    NameMappingKind = 0
	NameMappingFunction NameMappingKind = 1
	NameMappingIndex    NameMappingKind = 2
)

// ExplicitNameEntry maps a source name to a canonical name for a specific entity type.
type ExplicitNameEntry struct {
	// Kind identifies whether this mapping is for a table, function, or index.
	Kind NameMappingKind
	// SourceName is the name as defined in the module source.
	SourceName string
	// CanonicalName is the name used in system tables and client code generation.
	CanonicalName string
}

// RLSDef defines a row-level security policy using a SQL expression.
// The SQL expression is evaluated per-row per-client to determine visibility.
// Only rows for which the expression evaluates to true are visible to that client.
type RLSDef struct {
	// SQL is the row-level security SQL expression.
	SQL string
}

// ScheduleDef describes a scheduled reducer registration.
// The referenced table must have a column of type types.AlgebraicScheduleAt.
type ScheduleDef struct {
	// SourceName is an optional override name. If nil, the host generates a unique name.
	SourceName *string
	// TableName is the name of the table containing the schedule column.
	TableName string
	// ScheduleAtCol is the zero-based column index of the ScheduleAt field.
	ScheduleAtCol uint16
	// ReducerName is the name of the reducer to call.
	ReducerName string
}
